### ISSUE TITLE
Add Localisation System

### ISSUE THREAD

**Issue by ligthyear** [beavyHQ/beavy#24]
Beavy in its current state doesn't have support for Localization, that is showing strings and number in the locally expected language and patterns. We will be implementing a gettext-based system using pybabel and jed.The following needs to be done:

 - [x] integrate pybabel into flask
  - [x] add default language/locale config option
  - [x] add support for configuring available languages via config.yml
  - [x] add language preference on user model
  - [x] determine language by user or via user-agent or default (this order)
 - [x] build jed-i18n frontend module
 - [x] add toolchain to extract messages from both frontend and backend
   - [ ] allow these messages to be split up into core, modules, apps (using gettext domains?)
 - [x] add toolchain to compile latest messages with po2json (can we use webpack for that?)
   - [ ] allow "app" to overwrite all styles already defined
 - [x] let flask push translations to Jed via _preload
 - [ ] upgrade travis to:
   - [ ] automatically extract all messages when merging into master 
   - [ ] push latest version of those messages to transifix
 - [ ] add documentation about i18n
   - [x] how to use i18n in the backend
   - [ ] how to use i18n in the frontend
   - [ ] how to pull latest transifex translations and integrate them (tooling)

@ezmiller is on it!

**Comment by ligthyear** [comment]
I am in favor of choosing a framework/system we can integrate with [Transifex](https://www.transifex.com/product/automate/). Would be cool to push all translatable strings to transifex everytime we push stuff to master – and maybe automagically generate PRs to pull the translations back in.

**Comment by ligthyear** [comment]
Makes our lifes a hell of a lot easier, if we can get it to work with https://github.com/webpack/docs/wiki/list-of-plugins#i18nplugin

**Comment by ligthyear** [comment]
It appears we could use the same gettext-based system for frontend and backend actually:

 - [Flask Babel in the Backend](https://pythonhosted.org/Flask-Babel/) – see [the tutorial](http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xiv-i18n-and-l10n), too
 - [Babel itself to extract from both python and javascript](http://stackoverflow.com/questions/10267260/extracting-javascript-gettext-messages-using-babel-cli-extractor)
 - [use travis to send it](https://github.com/educloudalliance/educloud-bazaar/commit/5ca1b38f2382f354a8a648cba104e205a62ac4e7) to transifex [with the python client](https://pypi.python.org/pypi/transifex-client) – it even has badges (well, kinda)

Maybe even automagically pull latest changes once in a while?

**Comment by ezmiller** [comment]
@ligthyear we have to provide the translations right? i have a basic case working on the backend, but had to manually supply the translation.

**Comment by ligthyear** [comment]
@ezmiller what do you mean with "manually supply translation"? Did you push your work anywhere? Could you link to it, so I can take a look?

**Comment by ezmiller** [comment]
I'll push something this weekend. I was just wondering if the pybabel thing was supposed to attempt a translation, because when I ran the extraction, it just located the place in the code where the gettext or _() had been called, creating a key into a translation. But maybe supplying the translation is what the transifex piece is about?

**Comment by ezmiller** [comment]
@ligthyear so pybabel generates `mo` files for the backend. but the i18n-webpack-plugin expects `json`. in the pybabel docs i didn't see any utility for translating pot, po, or mo to json. we might need to handle this through some other tool. did you have any thoughts on this already?

**Comment by ligthyear** [comment]
@ezmiller: [po2json](https://github.com/mikeedwards/po2json#methods) should do the job, I'd say. which you could also used wrapped in the [po-loader](https://github.com/perchlayer/po-loader) but I think that is overkill for our case.

**Comment by ezmiller** [comment]
This is how po2json converted a test po file I had:

```
{
  "": {
    "project-id-version": "PROJECT VERSION",
    "report-msgid-bugs-to": "EMAIL@ADDRESS",
    "pot-creation-date": "2015-11-27 22:36+0000",
    "po-revision-date": "2015-11-27 14:46-0800",
    "language": "de",
    "language-team": "de <LL@li.org>",
    "plural-forms": "nplurals=2; plural=(n != 1);",
    "mime-version": "1.0",
    "content-type": "text/plain; charset=utf-8",
    "content-transfer-encoding": "8bit",
    "generated-by": "Babel 2.1.1",
    "last-translator": "",
    "x-generator": "Poedit 1.8.6"
  },
  "Welcome to Beavy!": [
    null,
    "Wilkommen zu Beavy!"
  ],
  "Hello": [
    null,
    ""
  ]
}
```
Seems rather strange. An empty string key leading into all the .po file headers? And why the null value in an arry for the translation keys themselves?

**Comment by ligthyear** [comment]
Looking at how the [i18n-Plugin works right now, it appears it wants a key-value-pair](https://github.com/webpack/i18n-webpack-plugin/blob/master/index.js#L95-L105). So maybe try passing the option `{format: 'mf'}`?

[From the docs](https://github.com/mikeedwards/po2json#methods):
>  format Defaults to raw.
>
>   - raw produces a "raw" JSON output
>   - jed produces an output that is 100% compatible with Jed < 1.1.0
>   - jed1.x produces an output that is 100% compatible with Jed >= 1.1.0
>   - **mf produces simple key:value output**.

**Comment by ligthyear** [comment]
Or maybe even use the jed format and run our own translator based on [JED](https://slexaxton.github.io/Jed/) ? Hmm... which reminds me that the current solution doesn't actually properly [deal with/support pluralization](https://github.com/webpack/i18n-webpack-plugin/issues/1) (the main reason, you never want to run your own i18n lib...).. Proposals?

**Comment by ligthyear** [comment]
This also sounds interesting: http://engineering.khanacademy.org/posts/i18n-babel-plugin.htm

**Comment by ezmiller** [comment]
oh that seems much much better, no? it's using react more natively, and gets rid of the whole bundle duplication.

**Comment by ezmiller** [comment]
The only problem might be they localization extraction process using pybabel. By default, it looks for `gettext()` and `__()`. You can add a -k to define an alternate marker that is should watch for, though. Maybe that'll work.

**Comment by ezmiller** [comment]
That looks promising. Trying to understand what the `$_()` syntax is. I also noticed [react-i18nliner](https://github.com/jenseng/react-i18nliner), but it seems to be a more complex soln that wouldn't necessarily work with our backend solution.

**Comment by ligthyear** [comment]
I also found https://github.com/alexkuz/redux-pagan – meant to be closer on the redux system . But the API is very ugly... (and I am not sure, that having this in the redux state makes a lot of sense to me ...)

**Comment by ligthyear** [comment]
It appear that the starter kit we are using is recommending [react-intl](https://github.com/yahoo/react-intl) (and I can see that point): https://github.com/erikras/react-redux-universal-hot-example/issues/278 – which now also starts to have [babel6 support](https://github.com/beavyHQ/beavy/pull/49)

**Comment by ligthyear** [comment]
After talking with @ezmiller directly, we concluded to do the following:

We will use [Jed](https://slexaxton.github.io/Jed/) to manage at-runtime gettext-style translations on Javascript and PyBabel inside flask. The following needs to be done:

 - [ ] integrate pybabel into flask
  - [ ] add default language/locale config option
  - [ ] add support for configuring available languages via config.yml
  - [ ] add language preference on user model
  - [ ] determine language by user or via user-agent or default (this order)
 - [ ] build jed-i18n frontend module
 - [ ] add toolchain to extract messages from both frontend and backend
   - [ ] allow these messages to be split up into core, modules, apps (using gettext domains?)
 - [ ] add toolchain to compile latest messages with po2json (can we use webpack for that?)
   - [ ] allow "app" to overwrite all styles already defined
 - [ ] let flask push translations to Jed via _preload
 - [ ] upgrade travis to:
   - [ ] automatically extract all messages when merging into master 
   - [ ] push latest version of those messages to transifix
 - [ ] add documentation about i18n
   - [ ] how to use i18n in the backend
   - [ ] how to use i18n in the frontend
   - [ ] how to pull latest transifex translations and integrate them (tooling)

@ezmiller is on it!

**Comment by ezmiller** [comment]
@ligthyear thanks for the todo-guide above. super helpful!

**Comment by ezmiller** [comment]
Possibly useful -- not sure yet what it is. Just noting it here: https://www.gnu.org/software/gettext/manual/html_node/msgcomm-Invocation.html

**Comment by ezmiller** [comment]
@ligthyear check out this weird problem I'm encontering: https://github.com/python-babel/flask-babel/issues/79

**Comment by ligthyear** [comment]
Turns out, gettext – especially on the frontend JS side – is a very unsatisfying solution to our problem. Let's investigate an ICU based system instead. For that we will have to.

- [ ] Create a new experimental branch (@ezmiller)
- [ ] Integrate ICU on the python side (@ezmiller )
  - [ ] add [PyICU](https://pypi.python.org/pypi/PyICU/) to python installation
  - [ ] research PyICU messages loading (how do we get the messages into PyICU)
  - [ ] integrate PyICU with Flask ([based on Flask-Babel](https://github.com/python-babel/flask-babel/tree/master/flask_babel)?, separate github repo in Beavy?!?)
  - [ ] research how message extraction works with PyICU
 - [ ] [Integrate React-Intl](https://github.com/yahoo/react-intl/issues/162) (@lightyear)
   - [ ] message extraction with [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl)
   
Also to be done after the research
 - [ ] merging backend and frontend messages (do we want to do that? probably?)
 - [ ] send translates from backend to frontend as planned before
 - [ ] integrate into travis build

**Comment by ligthyear** [comment]
@ezmiller with my [latest commit](https://github.com/beavyHQ/beavy/commit/233ca5697a4ee31ed46353ec3322344a3cbdcf0b) we now have transifex ready message extraction for react-intl.

Just run `npm run extract-messages` and you'll find all messages bundled in module, app and core in `var/react-intl-messages`. I believe we could then just use the transifex command line client to upload them directly. Please correct me if I am wrong/we are missing something else.

**Comment by ezmiller** [comment]
@ligthyear Nice! Taking a look now.

**Comment by ezmiller** [comment]
@ligthyear Regarding the transifex integration, the question is whether we want to create a transifex "resource" for each new module and app, or instead lump them together in a frontend json file? If we keep them separate, we'd need to register each new resource either via the API or the cli tool so that transifex will know to push them.

**Comment by ezmiller** [comment]
@ligthyear here's one transifex setup:

```
# initialize the whole transifex setup, only done once i think, though one thing it does is add a .transifexrc # file to home directory of the current user that includes password credentials for transifex, so not sure how we'd handle that.
tx init

# these commands setup the translations "resources" for each individual set. if we're just gonna have server/frontend etc, that could be just two, otherwise when a new app/module is added a command liek these would need to be run.
tx set -t KEYVALUEJSON --auto-local -r beavy.server 'translations/beavy.server/<lang>/<lang>.json' --source-lang en --source-file var/server-messages/server-messages.json --execute
tx set -t KEYVALUEJSON --auto-local -r beavy.core 'translations/beavy.core/<lang>/<lang>.json' --source-lang en --source-file var/react-intl-messages/beavy-core.json --execute

# then you push the source files
tx push -s -t

# do the translations on transifex

# then pull them down
tx pull -a 
```

the transifex config file that results from the above `set` commands looks like this:
```
[main]
host = https://www.transifex.com

[beavy.server]
file_filter = translations/beavy.server/<lang>/<lang>.json
source_file = var/server-messages/server-messages.json
source_lang = en
type = KEYVALUEJSON

[beavy.core]
file_filter = translations/beavy.core/<lang>/<lang>.json
source_file = var/react-intl-messages/beavy-core.json
source_lang = en
type = KEYVALUEJSON
```

**Comment by ligthyear** [comment]
Regarding transifex, we can also store the auth-credentials locally in the
project in an `.transifexrc` file - see
http://docs.transifex.com/client/config/#transifexrc (the italic paragraph
at the end). But as it properly states we shouldn't commit it as is to the
repo. Fortunately Travis allows us to commit encrypted files only Travis is
able to decrypt - see
https://docs.travis-ci.com/user/encrypting-files/#Automated-Encryption . So
if we do that with the auth-credentials, we should be good.

Aside from push and pull, it appears the other transifix commands mainly
help with configuration of the project. However this appears to be a
one-time thing (mostly) for whenever we added a new app or module. So,
that's not really a problem, is it?

Re Resources:
My script currently skips all occurrences of translation keys in the
modules and apps, which are already specified in core. If we do a similar
thing with the backend I don't see any problem with having things split up.
So I'd vote for `core.server`, `core.web`, `comments-module.web`, ... etc
(using 'web' instead of frontend/JavaScript to allow us to define other
frontends later, like let's say iOS or android).

Sound good?

**Comment by ezmiller** [comment]
Yes this makes sense. One thing: the naming convention for transifex resources is, I think, <project_name>.<resource>, so if we do something like core.* and then module-name-.web, we'd need to maintain each module as a project within the BeavyHQ organization. But maybe that actually makes sense? Or maybe something like:

```
# for beavy core
beavy.server
beavy.web

# for modules
comments-module.web

# and for apps
trellis.server
trellis.web
```
Will apps or modules modify server side localization?

**Comment by ezmiller** [comment]
@ligthyear an interesting approach to the problem we are trying to solve -- internationalization for React -- here as well: http://blog.getsentry.com/2016/01/07/react-i18n.html

**Comment by ezmiller** [comment]
Just some examples here for how to use ICU's `MessageFormat` class:

assuming: 
```
from icu import MessageFormat, Formattable
```

For a msg with no args (this works but seems off):
```
msg = MessageFormat('house')
msg.format('')
=> "house"
```

For a message with one arg:
```
msg = MessageFormat('{name} likes this')
msg.format(['name'], [Formattable('john')])
=> "johnlikes this"
```

For a message with multiple args:
```
msg = MessageFormat('{name1} and {name2} like this')
arg_names = ['name1', 'name2']
args = [Formattable('susan'), Formattable('sally')]
msg.format(arg_names, args)
=> "susan and sally like this" 
```

good resource, the pyicu testing file for MessageFormat: https://github.com/ovalhub/pyicu/blob/master/test/test_MessageFormat.py
